export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_RESPONSE = 'GET_NEWS_RESPONSE';
export const END_CALIBRATION = 'END_CALIBRATION';
export const INIT_CALIBRATION = 'INIT_CALIBRATION';